@startuml
!theme mars

rectangle UMLTypes {
    class Diagram{
        classes: List[Class]
    }

    class Class{
        name: str
        attributes
        methods
    }
    class Method{
        name: str
        params
        returnType: str
    }

    class Attribute{
        name: str
        type: str
    }

    class Parameter{
        name: str
        type: str
    }


    Class *-down-> Attribute
    Class *-> Method
    Method *-down-> Parameter
    Method -[hidden]right- Attribute
    Diagram *-> Class
}

rectangle Decorator {
    class IncludeInUML{
    }
}



rectangle Services {
    class ClassRepository {
        - classes: List[type]
        + add(cls: type)
        + get_all(): List[type]
    }
    class TypeHintService{
        get_type_hints(func: Callable) -> dict[str, type])
        get_type_hints(cls: class) -> dict[str, type])
    }

    class MethodFactory{
        create_method()
    }

    class AttributeFactory{
        create_attribute()
    }

    class ClassFactory{
        create_class()
    }

    ClassFactory ..> MethodFactory: uses
    ClassFactory ..> AttributeFactory: uses

    MethodFactory ..> TypeHintService: uses
    AttributeFactory ..> TypeHintService: uses
}

rectangle Diagrams{
    class DiagramService {
        generate_diagram() : str
    }

    class DiagramFactory{
        create_uml_diagram()
    }
    DiagramService ...> DiagramFactory: uses
}

rectangle PlantUML{
    class PlantUMLDiagramService{
        convert(diagram: UMLTypes.Diagram) -> str
    }
    class ClassConverter{
        convert(cls: UMLTypes.IncludeInUML) -> str
    }

    class AttributeConverter{
        convert(attr: UMLTypes.Attribute) -> str
    }

    class PlantUMLMethodConverter{
        convert(method: UMLTypes.Method) -> str
    }

    class PlantUMLRenderer{
        render(diagram: str)
    }
    PlantUMLDiagramService ..> ClassConverter: uses
    ClassConverter ..> AttributeConverter: uses
    ClassConverter ..> PlantUMLMethodConverter: uses
}

' Decorator Relations
Decorator.IncludeInUML .down.> ClassRepository: uses

' PlantUML Relations:

ClassConverter ..> UMLTypes.Class: converts
AttributeConverter ..> UMLTypes.Attribute: converts
PlantUMLMethodConverter ..> UMLTypes.Method: converts


' Services Relations:
DiagramFactory ...> ClassFactory
DiagramFactory ...> ClassRepository: uses
DiagramFactory ..> UMLTypes.Diagram

' Diagrams Relations:
PlantUMLDiagramService .. UMLTypes.Diagram: converts
DiagramService ..> PlantUMLDiagramService: uses
DiagramService ..> PlantUMLRenderer: uses

@enduml