[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pdgen"
version = "0.1.5"
authors = [{name="Tobias Bück", email="tab@softoft.de"}]
description = "A Python package for generating UML diagrams from Python code using PlantUML."
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13"
]
requires-python = ">=3.12"
dependencies = [
    "build",
    "certifi",
    "charset-normalizer",
    "colorama",
    "docutils",
    "httplib2",
    "idna",
    "importlib_metadata",
    "jaraco.classes",
    "jaraco.context",
    "jaraco.functools",
    "keyring",
    "markdown-it-py",
    "mdurl",
    "more-itertools",
    "nh3",
    "packaging",
    "pkginfo",
    "plantuml",
    "Pygments",
    "pyparsing",
    "pyproject_hooks",
    "pywin32-ctypes",
    "readme_renderer",
    "requests",
    "requests-toolbelt",
    "rfc3986",
    "rich",
    "setuptools",
    "six",
    "twine",
    "urllib3",
    "wheel",
    "zipp"
]
[project.urls]
"Bug Reports" = "https://github.com/Softoft/pdgen/issues"
Source = "https://github.com/Softoft/pdgen/"
