[tool.poetry]
name = "pdgen"
version = "0.2.3"
description = ""
authors = ["Softoft <tobias.bueck@softoft.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "[3.12, 3.13]"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
